### ISSUE TITLE
Add Class - API call - POST

### ISSUE THREAD

**Issue by joshthomas735** [PositiveSpaceDevelopment/Grupr#59]
backend needs to create a post request api call called /addclass that allows the front end to send the database a list of the class name and number pairs for the classes that the user added to their profile. These classes should be 'paired' with the user profile in the database so that later on, we can retrieve all of the classes associated with a specific user

**Comment by BryceStevenson** [comment]
Updating to reflect changes from meeting. 

New address is /createclass to reflect to apiary.

Front end will send a class subject and number, back end will check if the class is already in the database. If it is not add the class, then add it to the user. If it is, add to the user profile.

**Comment by BryceStevenson** [comment]
@joshthomas735 

Do you want the function to return true if successful.
